"""add office number

Revision ID: fc626862c6fa
Revises: 72a7a662a714
Create Date: 2022-11-22 16:44:07.502478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc626862c6fa'
down_revision = '72a7a662a714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('office_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'office_number')
    # ### end Alembic commands ###
