version: '3.8'
services:

  db:
    container_name: pg_fastapi
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: fastapi
    ports:
      - "5434:5432"

  pgadmin:
    container_name: pgadmin4_fastapi
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: surasit.pongpanna@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres123
    ports:
      - "5051:80"